import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import HomeMenuItem from '@/components/HomeMenuItem'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Seb Fousse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className="container m-auto flex flex-row flex-wrap 2xl:justify-center xl:justify-center lg:justify-start md:justify-start sm:justify-start">
            
          <div className="splash-image">
            <figure>
              <Image 
                src="/gifs/face-morph.gif"
                width={750} height={750} 
                alt="Morphing self portrait"/>                                                
            </figure>
          </div>

          <div className="title-and-menu px-4 md:px-4 lg:px-8 xl:px-16 2xl:px-16">
            
            <div className="title word space-y-2 font-bold py-8 text-6xl md:text-8xl lg:text-7xl xl:text-5xl 2xl:text-8xl">
              <h1 className={styles.firstName}>
                Seb<span className={styles.extra}>astien</span>
              </h1>
              <h1>
                Foussé
              </h1>
            </div>

            <div className="menu space-y-4 md:space-y-8 lg:space-y-8 xl:space-y-8 2xl:space-y-8 font-medium text-4xl md:text-4xl lg:text-4xl xl:text-4xl 2xl:text-6xl">
              
              <HomeMenuItem text="*projects" href="/projects"></HomeMenuItem>
              <HomeMenuItem text="*about" href="/about"></HomeMenuItem>
              <HomeMenuItem text="*email" href="mailto:me@sebf.xyz"></HomeMenuItem>
              <HomeMenuItem text="*instagram" href="https://www.instagram.com/sebf.xyz/"></HomeMenuItem>

            </div>
          </div>
        </div>
      </main>
    </>
  )
}
