import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      {/*<Script src="/js/enhance_menu.js"/>*/}
      <Head>
        <title>Seb Fousse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className="container m-auto flex flex-row flex-wrap 2xl:justify-center xl:justify-center lg:justify-start md:justify-start sm:justify-start">
            
          <div className="splash-image">
            <figure>
              <Image 
                src="/gifs/face-morph.gif"
                width={750} height={750} 
                alt="Morphing self portrait"/>                                                
            </figure>
          </div>

          <div className="title-and-menu px-4 md:px-4 lg:px-8 xl:px-16 2xl:px-16">
            
            <div className="title word space-y-2 font-bold py-8 text-6xl md:text-8xl lg:text-7xl xl:text-5xl 2xl:text-8xl">
              <h1 className={styles.firstName}>
                Seb<span className={styles.extra}>astien</span>
              </h1>
              <h1>
                Foussé
              </h1>
            </div>

            <div className="menu space-y-2 md:space-y-4 lg:space-y-4 xl:space-y-4 2xl:space-y-4 font-medium text-4xl md:text-4xl lg:text-4xl xl:text-4xl 2xl:text-6xl">

              {/* Projects Link */}
              <div className={styles.option}>
                <Link className={styles.fancy} id="projects" href="/projects">
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-1835ms"}}>
                      <span class="letter" style={{animationDelay: "0ms"}}>*</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-4907ms"}}>
                      <span class="letter" style={{animationDelay: "1000ms"}}>p</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-4281ms"}}>
                      <span class="letter" style={{animationDelay: "2000ms"}}>r</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-3108ms"}}>
                      <span class="letter" style={{animationDelay: "3000ms"}}>o</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-4633ms"}}>
                      <span class="letter" style={{animationDelay: "4000ms"}}>j</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-4517ms"}}>
                      <span class="letter" style={{animationDelay: "5000ms"}}>e</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-1815ms"}}>
                      <span class="letter" style={{animationDelay: "6000ms"}}>c</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-916ms"}}>
                      <span class="letter" style={{animationDelay: "7000ms"}}>t</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-2558ms"}}>
                      <span class="letter" style={{animationDelay: "8000ms"}}>s</span>
                    </span>
                  </span>
                </Link>
              </div>

              <div className={styles.option}>
                <Link className={styles.fancy} id="about" href="/about">
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-1835ms"}}>
                      <span class="letter" style={{animationDelay: "0ms"}}>*</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-4907ms"}}>
                      <span class="letter" style={{animationDelay: "1000ms"}}>a</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-4281ms"}}>
                      <span class="letter" style={{animationDelay: "2000ms"}}>b</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-3108ms"}}>
                      <span class="letter" style={{animationDelay: "3000ms"}}>o</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-4633ms"}}>
                      <span class="letter" style={{animationDelay: "4000ms"}}>u</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-4517ms"}}>
                      <span class="letter" style={{animationDelay: "5000ms"}}>t</span>
                    </span>
                  </span>
                </Link>
              </div>

              <div className={styles.option}>
                <a className={styles.fancy} id="email" href="mailto:me@sebf.xyz">
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-1835ms"}}>
                      <span class="letter" style={{animationDelay: "0ms"}}>*</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-4907ms"}}>
                      <span class="letter" style={{animationDelay: "1000ms"}}>e</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-4281ms"}}>
                      <span class="letter" style={{animationDelay: "2000ms"}}>m</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-3108ms"}}>
                      <span class="letter" style={{animationDelay: "3000ms"}}>a</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-4633ms"}}>
                      <span class="letter" style={{animationDelay: "4000ms"}}>i</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-4517ms"}}>
                      <span class="letter" style={{animationDelay: "5000ms"}}>l</span>
                    </span>
                  </span>
                </a>
              </div>

              <div className={styles.option}>
                <a href="https://www.instagram.com/sebf.xyz/" className={styles.fancy} id="instagram">
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-2454ms"}}>
                      <span class="letter" style={{animationDelay: "0ms"}}>*</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-2915ms"}}>
                      <span class="letter" style={{animationDelay: "1000ms"}}>i</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-976ms"}}>
                      <span class="letter" style={{animationDelay: "2000ms"}}>n</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-4517ms"}}>
                      <span class="letter" style={{animationDelay: "3000ms"}}>s</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-3759ms"}}>
                      <span class="letter" style={{animationDelay: "4000ms"}}>t</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-1220ms"}}>
                      <span class="letter" style={{animationDelay: "5000ms"}}>a</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-2937ms"}}>
                      <span class="letter" style={{animationDelay: "6000ms"}}>g</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-4982ms"}}>
                      <span class="letter" style={{animationDelay: "7000ms"}}>r</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-2612ms"}}>
                      <span class="letter" style={{animationDelay: "8000ms"}}>a</span>
                    </span>
                  </span>
                  <span class="outer">
                    <span class="inner" style={{animationDelay: "-1904ms"}}>
                      <span class="letter" style={{animationDelay: "9000ms"}}>m</span>
                    </span>
                  </span>
                </a>
              </div>

            </div>
          </div>

          

        </div>

      </main>
    </>
  )
}
